### ISSUE TITLE
V2 Hosted Service Upgrade 

### ISSUE THREAD

**Issue by SvenMuller95** [bankless-academy/explorer-indexer#1]
Hey Didier 

I hope you are well! It's great to see a multi-chain indexer for the Bankless Academy. 

I don't think we have an existing thread with you, hence creating an issue here and hoping to connect with you more. I'll share my tg further below. 

Reason for connecting is that we are looking to decommission our V1-hosted service, and have been making announcements and emails in this regard over the last few weeks. I'm not sure if you are aware of this hence I'm here :) 

We've asked our partners to migrate to the V2-hosted service, and it requires a simple push to the same branch which will then auto-deploy to the V2-Explorer: https://v2.envio.dev/explorer

The only caveat is that the V2-hosted service requires minimum indexers version v2.6.0 and i think you current indexer is V2.5.2: https://envio.dev/app/bankless-academy/explorer-indexer

This should be a quick update as it's a recent version. 

Sharing a page on transition & FAQ. and the indexer would fit the dev tier so pricing is also N/A. 
https://www.notion.so/envio-dev/V2-Hosted-Service-Transition-and-FAQs-12faf438121380c98ec7f7626c9f9f83

My tg is Sven_Muller

**Comment by SvenMuller95** [comment]
Hey @didierkrux , further to the above, we plan to decommission all V1-hosted indexers this Frida at 1pm GMT. A simple push would redeploy the indexer to v2-hosted service.

**Comment by didierkrux** [comment]
Thanks for the heads up @SvenMuller95.
I just did the migration to v2 hosting.
